plugins {
    id 'java-library'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.107'
}

group = mod_group_id

def formatted_mod_version = "${mod_version}+c${create_version}.mc${minecraft_version}"

version = formatted_mod_version

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

base {
    archivesName = mod_id
}

neoForge { 
    version = neoforge_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'forge.logging.console.level', 'debug'
        }

        client {
            client()
            programArgument '-XX:+AllowEnhancedClassRedefinition'
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }

        server {
            server()
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
            programArgument '--nogui'
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }

        data {
            data()

//            programArguments.addAll '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
    }

    maven { url = "https://maven.createmod.net" }
}

configurations {
    createMod
}

def extractedPonderJar = layout.buildDirectory.file("create-subjars/ponder.jar")
def extractPonderJar = tasks.register("extractPonderJar", Copy) {
    from({ zipTree(configurations.createMod.singleFile) }) {
        include "META-INF/jarjar/ponder-neoforge-*.jar"
        eachFile { path = name }
        includeEmptyDirs = false
        rename { "ponder.jar" }
    }
    into extractedPonderJar.get().asFile.parentFile
}

dependencies {
    implementation "net.neoforged:neoforge:${neoforge_version}"

    createMod "maven.modrinth:create:${create_version}+mc${minecraft_version}"
    implementation "maven.modrinth:create:${create_version}+mc${minecraft_version}"
    compileOnly(files(extractedPonderJar).builtBy(extractPonderJar))

    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

tasks.named('compileJava').configure {
    dependsOn extractPonderJar
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [minecraft_version   : minecraft_version, minecraft_version_range: minecraft_version_range,
                             neoforge_version    : neoforge_version, 
                             loader_version_range: loader_version_range,
                             mod_id              : mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: formatted_mod_version,
                             mod_authors         : mod_authors, mod_description: mod_description,
                             create_version      : create_version]

    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

tasks.named('jar', Jar).configure {
    manifest {
        attributes(["Specification-Title"     : mod_id,
                    "Specification-Vendor"    : mod_authors,
                    "Specification-Version"   : "1",
                    "Implementation-Title"    : project.name,
                    "Implementation-Version"  : project.jar.archiveVersion,
                    "Implementation-Vendor"   : mod_authors,
                    "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")])
    }

    archiveBaseName.set("ASMP_${mod_id}")
    archiveVersion.set(formatted_mod_version)
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

